tags:
  - Tasks
summary: Get all tasks
description: Retrieve a paginated list of tasks with optional filtering and sorting
parameters:
  - name: page
    in: query
    description: Page number for pagination
    required: false
    schema:
      type: integer
      minimum: 1
      default: 1
      example: 1
  - name: perPage
    in: query
    description: Number of tasks per page
    required: false
    schema:
      type: integer
      minimum: 1
      maximum: 100
      default: 10
      example: 10
  - name: sortBy
    in: query
    description: Field to sort by
    required: false
    schema:
      type: string
      enum:
        [
          _id,
          title,
          description,
          isDone,
          priority,
          category,
          dueDate,
          createdAt,
          updatedAt,
        ]
      default: createdAt
      example: priority
  - name: sortOrder
    in: query
    description: Sort order
    required: false
    schema:
      type: string
      enum: [asc, desc]
      default: asc
      example: desc
  - name: priority
    in: query
    description: Filter by priority level
    required: false
    schema:
      type: integer
      minimum: 1
      maximum: 10
      example: 5
  - name: isDone
    in: query
    description: Filter by completion status
    required: false
    schema:
      type: boolean
      example: false
  - name: category
    in: query
    description: Filter by category
    required: false
    schema:
      type: string
      enum:
        [
          work,
          personal,
          health,
          education,
          finance,
          home,
          shopping,
          travel,
          social,
          hobby,
        ]
      example: work
  - name: dueDate
    in: query
    description: Filter by due date
    required: false
    schema:
      type: string
      format: date-time
      example: '2024-09-15T10:00:00.000Z'
responses:
  '200':
    description: Successfully found tasks
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: 'Successfully found tasks!'
            data:
              $ref: '../../components/schemas/PaginatedTasks.yaml'
  '400':
    $ref: '../../components/responses/BadRequest.yaml'
  '500':
    $ref: '../../components/responses/InternalServerError.yaml'
